// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFItecGYbkOEvapn_leTBYySFuwOGLUYU',
    appId: '1:689035209444:web:e2751a618a082d072cdaf1',
    messagingSenderId: '689035209444',
    projectId: 'sample-faa26',
    authDomain: 'sample-faa26.firebaseapp.com',
    storageBucket: 'sample-faa26.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEXshnJfxOvJkqOalffwgwb7Fu2QVxh1E',
    appId: '1:689035209444:android:8b4295f5e34bda6c2cdaf1',
    messagingSenderId: '689035209444',
    projectId: 'sample-faa26',
    storageBucket: 'sample-faa26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmfmFoppF7PFTTXJRF7prSz9qXXTMUlhU',
    appId: '1:689035209444:ios:ace5d260077ca3ba2cdaf1',
    messagingSenderId: '689035209444',
    projectId: 'sample-faa26',
    storageBucket: 'sample-faa26.appspot.com',
    iosBundleId: 'com.example.samplePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmfmFoppF7PFTTXJRF7prSz9qXXTMUlhU',
    appId: '1:689035209444:ios:2047764dc89660a62cdaf1',
    messagingSenderId: '689035209444',
    projectId: 'sample-faa26',
    storageBucket: 'sample-faa26.appspot.com',
    iosBundleId: 'com.example.samplePractice.RunnerTests',
  );
}
